// <auto-generated />
using System;
using ECommerce.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce.Data.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20240511084045_UpdateOrderTbl_AddOrderCode")]
    partial class UpdateOrderTbl_AddOrderCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccountName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("BankImage")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("BankId");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BannerPath")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("BannerId");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogContent")
                        .HasColumnType("ntext");

                    b.Property<byte?>("BlogPosition")
                        .HasColumnType("tinyint");

                    b.Property<string>("BlogTitle")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("BlogId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("AddressUrl")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("FaviconPath")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("LogoPath")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("WebsiteName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Header", b =>
                {
                    b.Property<int>("HeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeaderName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte?>("HeaderPosition")
                        .HasColumnType("tinyint");

                    b.Property<string>("HeaderUrl")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("HeaderId");

                    b.ToTable("Header");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Cms.Social", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<byte?>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("SocialName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SocialUrl")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("SocialId");

                    b.ToTable("Social");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Common.District", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Common.Province", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AdministrativeRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Common.Ward", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AdministrativeUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.Attribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AttributeId");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("OptionId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.OptionValue", b =>
                {
                    b.Property<int>("OptionValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsBaseValue")
                        .HasColumnName("isBaseValue")
                        .HasColumnType("bit");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionValueName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("OptionValueId");

                    b.HasIndex("OptionId");

                    b.ToTable("OptionValue");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("SizeGuideId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SizeGuideId");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategoryAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("AttributeId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("SubCategoryAttribute");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategoryOption", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.HasKey("SubCategoryId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("SubCategoryOption");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.OmsSchema.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiscountCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("DiscountStock")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ForBrand")
                        .HasColumnName("forBrand")
                        .HasColumnType("bit");

                    b.Property<bool?>("ForGlobal")
                        .HasColumnName("forGlobal")
                        .HasColumnType("bit");

                    b.Property<bool?>("ForShop")
                        .HasColumnName("forShop")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPercent")
                        .HasColumnName("isPercent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("DiscountId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.OmsSchema.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WardCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CityCode");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("WardCode");

                    b.ToTable("Orders","oms");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.OmsSchema.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceOnSell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails","oms");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandImagePath")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("DescriptionTitle")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Highlights")
                        .HasColumnType("bit");

                    b.Property<bool?>("New")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.BrandCategory", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BrandId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BrandCategory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Interest", b =>
                {
                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Liked")
                        .HasColumnType("bit");

                    b.HasKey("RateId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Delivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte?>("DiscountPercent")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("DiscountPreOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Highlights")
                        .HasColumnType("bit");

                    b.Property<string>("Insurance")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool?>("Legit")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("ntext");

                    b.Property<bool?>("New")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Ppc")
                        .HasColumnName("PPC")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<decimal?>("PriceAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceForSeller")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceImport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PricePreOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProductAddedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ProductDescription")
                        .HasColumnType("ntext");

                    b.Property<string>("ProductDescriptionMobile")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ProductImportDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar")
                        .HasMaxLength(100);

                    b.Property<byte?>("ProductRate")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ProductStock")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitForSeller")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitPreOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Repay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("SizeGuide")
                        .HasColumnType("ntext");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ShopId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductAttribute", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("ProductId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImagePath")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductOptionValue", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OptionValueId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "OptionValueId");

                    b.HasIndex("OptionValueId");

                    b.ToTable("ProductOptionValue");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductPrice", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("PriceOnSell")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductPrice");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductTypeName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductUserImage", b =>
                {
                    b.Property<int>("ProductUserImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductUserImagePath")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("ProductUserImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductUserImage");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("HtmlPosition")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("IdsToDelete")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("RateValue")
                        .HasColumnType("int");

                    b.Property<int?>("RepliedId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRepliedId")
                        .HasColumnType("int");

                    b.HasKey("RateId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRepliedId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.RatingImage", b =>
                {
                    b.Property<int>("RatingImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RateId")
                        .HasColumnType("int");

                    b.Property<string>("RatingImagePath")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("RatingImageId");

                    b.HasIndex("RateId");

                    b.ToTable("RatingImage");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("ShopAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShopCityCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ShopDistrictCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ShopJoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShopMail")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShopPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ShopWardCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Tax")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShopId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ShopBank", b =>
                {
                    b.Property<int>("ShopBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShopAccountName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ShopAccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("ShopBankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("ShopBankId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopBank");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ShopBrand", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.HasKey("ShopId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("ShopBrand");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.SizeGuide", b =>
                {
                    b.Property<int>("SizeGuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsBaseSizeGuide")
                        .HasColumnName("isBaseSizeGuide")
                        .HasColumnType("bit");

                    b.Property<string>("SizeContent")
                        .HasColumnType("ntext");

                    b.HasKey("SizeGuideId");

                    b.ToTable("SizeGuide");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.MessageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachment")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FromName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FromPhoneNumber")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ToPhoneNumber")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("MessageHistory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("JsLink")
                        .HasColumnType("ntext");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("ntext");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.OnlineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AccessDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OnlineHistory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Module")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = "ACCESS_ALL",
                            Name = "ACCESS_ALL"
                        },
                        new
                        {
                            Id = "COMMON_CREATE",
                            Module = "COMMON",
                            Name = "COMMON_CREATE"
                        },
                        new
                        {
                            Id = "COMMON_READ",
                            Module = "COMMON",
                            Name = "COMMON_READ"
                        },
                        new
                        {
                            Id = "COMMON_UPDATE",
                            Module = "COMMON",
                            Name = "COMMON_UPDATE"
                        },
                        new
                        {
                            Id = "COMMON_DELETE",
                            Module = "COMMON",
                            Name = "COMMON_DELETE"
                        },
                        new
                        {
                            Id = "USER_LIST_CREATE",
                            Module = "USER",
                            Name = "USER_LIST_CREATE"
                        },
                        new
                        {
                            Id = "USER_LIST_READ",
                            Module = "USER",
                            Name = "USER_LIST_READ"
                        },
                        new
                        {
                            Id = "USER_LIST_UPDATE",
                            Module = "USER",
                            Name = "USER_LIST_UPDATE"
                        },
                        new
                        {
                            Id = "USER_LIST_DELETE",
                            Module = "USER",
                            Name = "USER_LIST_DELETE"
                        },
                        new
                        {
                            Id = "USER_DETAIL_CREATE",
                            Module = "USER",
                            Name = "USER_DETAIL_CREATE"
                        },
                        new
                        {
                            Id = "USER_DETAIL_READ",
                            Module = "USER",
                            Name = "USER_DETAIL_READ"
                        },
                        new
                        {
                            Id = "USER_DETAIL_UPDATE",
                            Module = "USER",
                            Name = "USER_DETAIL_UPDATE"
                        },
                        new
                        {
                            Id = "USER_DETAIL_DELETE",
                            Module = "USER",
                            Name = "USER_DETAIL_DELETE"
                        },
                        new
                        {
                            Id = "ORDER_CREATE",
                            Module = "ORDER",
                            Name = "ORDER_CREATE"
                        },
                        new
                        {
                            Id = "ORDER_READ",
                            Module = "ORDER",
                            Name = "ORDER_READ"
                        },
                        new
                        {
                            Id = "ORDER_UPDATE",
                            Module = "ORDER",
                            Name = "ORDER_UPDATE"
                        },
                        new
                        {
                            Id = "ORDER_DELETE",
                            Module = "ORDER",
                            Name = "ORDER_DELETE"
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.RoleToPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RoleToPermissions");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSystemAccount")
                        .HasColumnName("isSystemAccount")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserCityCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserCityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDistrictCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UserJoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserMail")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserWardCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserWardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.OptionValue", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.Option", "Option")
                        .WithMany("OptionValues")
                        .HasForeignKey("OptionId")
                        .HasConstraintName("FK_OptionValue_Option")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategory", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_SubCategory_Category")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.SizeGuide", "SizeGuide")
                        .WithMany("SubCategories")
                        .HasForeignKey("SizeGuideId")
                        .HasConstraintName("FK_SubCategory_SizeGuide");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategoryAttribute", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.Attribute", "Attribute")
                        .WithMany("SubCategoryAttributes")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("FK_SubCategoryAttribute_Attribute")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.Inventory.SubCategory", "SubCategory")
                        .WithMany("SubCategoryAttributes")
                        .HasForeignKey("SubCategoryId")
                        .HasConstraintName("FK_SubCategoryAttribute_SubCategory")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.SubCategoryOption", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.Option", "Option")
                        .WithMany("SubCategoryOptions")
                        .HasForeignKey("OptionId")
                        .HasConstraintName("FK_SubCategoryOption_Option")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.Inventory.SubCategory", "SubCategory")
                        .WithMany("SubCategoryOptions")
                        .HasForeignKey("SubCategoryId")
                        .HasConstraintName("FK_SubCategoryOption_SubCategory")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.OmsSchema.Order", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Common.Province", "City")
                        .WithMany()
                        .HasForeignKey("CityCode");

                    b.HasOne("ECommerce.Data.Entities.Common.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictCode");

                    b.HasOne("ECommerce.Data.Entities.Common.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardCode");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.OmsSchema.OrderDetail", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.OmsSchema.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Brand", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.OmsSchema.Discount", "Discount")
                        .WithMany("Brands")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Brand_Discount");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.BrandCategory", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Brand", "Brand")
                        .WithMany("BrandCategories")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_BrandCategory_Brand")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.Inventory.Category", "Category")
                        .WithMany("BrandCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_BrandCategory_Category")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Interest", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Rate", "Rate")
                        .WithMany("Interests")
                        .HasForeignKey("RateId")
                        .HasConstraintName("FK_Interest_Rate")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Interest_User")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Product", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Product_Brand")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("FK_Product_Shop")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.Inventory.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .HasConstraintName("FK_Product_SubCategory")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductAttribute", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.Attribute", "Attribute")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("FK_ProductAttribute_Attribute")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductAttribute_Product")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductImage_Product")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductOptionValue", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Inventory.OptionValue", "OptionValue")
                        .WithMany("ProductOptionValues")
                        .HasForeignKey("OptionValueId")
                        .HasConstraintName("FK_ProductOptionValue_OptionValue")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("ProductOptionValues")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductOptionValue_Product")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductPrice", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductPrice_Product")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.ProductType", "ProductType")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK_ProductPrice_ProductType")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ProductUserImage", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("ProductUserImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_ProductUserImage_Product");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Rate", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Product", "Product")
                        .WithMany("Rates")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Rate_Product");

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "User")
                        .WithMany("RateUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Rate_User");

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "UserReplied")
                        .WithMany("RateUserReplieds")
                        .HasForeignKey("UserRepliedId")
                        .HasConstraintName("FK_Rate_UserReplied");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.RatingImage", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Rate", "Rate")
                        .WithMany("RatingImages")
                        .HasForeignKey("RateId")
                        .HasConstraintName("FK_RatingImage_Rate");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.Shop", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.OmsSchema.Discount", "Discount")
                        .WithMany("Shops")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Shop_Discount");

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "User")
                        .WithMany("Shops")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Shop_User");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ShopBank", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Shop", "Shop")
                        .WithMany("ShopBanks")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("FK_ShopBank_Shop")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.ProductSchema.ShopBrand", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Brand", "Brand")
                        .WithMany("ShopBrands")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_ShopBrand_Brand")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.ProductSchema.Shop", "Shop")
                        .WithMany("ShopBrands")
                        .HasForeignKey("ShopId")
                        .HasConstraintName("FK_ShopBrand_Shop")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.Notification", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "Receiver")
                        .WithMany("NotificationReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_Notification_User");

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "Sender")
                        .WithMany("NotificationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Notification_User1");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.RoleToPermission", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.UserSchema.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.UserSchema.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Data.Entities.UserSchema.UserRole", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.UserSchema.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserRole_Role")
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Entities.UserSchema.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserRole_User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
