name: Deploy to Plesk

on:
  push:
    branches:
      - deploy/prod
      - workout/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef --version 3.1.8

      - name: Restore dependencies
        run: dotnet restore ECommerce.WebApp/ECommerce.WebApp.csproj

      - name: Build
        run: dotnet build --configuration Release ECommerce.WebApp/ECommerce.WebApp.csproj --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ECommerce.WebApp/ECommerce.WebApp.csproj

      - name: Save publish output
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download publish output
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./publish

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /httpdocs/
          exclude: 'wwwroot/**' # Example exclusion, adjust as needed
          timeout: 120000 # Optional: Timeout in milliseconds