name: Deploy to Plesk

on:
  push:
    branches:
      - workout/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef --version 3.1.8

      - name: Restore dependencies
        run: dotnet restore ECommerce.WebApp/ECommerce.WebApp.csproj

      - name: Build
        run: dotnet build --configuration Release ECommerce.WebApp/ECommerce.WebApp.csproj --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ECommerce.WebApp/ECommerce.WebApp.csproj

      - name: Save publish output
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download publish output
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./publish
      
      - name: Prepare to shut down
        shell: bash
        run: |
          mkdir tmp
          echo "" > tmp/app_offline.htm

      - name: Shutting down...
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./tmp/
          server-dir: /httpdocs/
          exclude: |
            !**
          timeout: 1200000
      
      - name: Prepare to deploy
        uses: MintPlayer/github-actions/delay@v3
        with:
          milliseconds: 5000

      - name: Deploying...
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /httpdocs/
          exclude: |
            app_offline.htm
            wwwroot/** 
          timeout: 1200000

      - name: Prepare to turn on
        uses: MintPlayer/github-actions/delay@v3
        with:
          milliseconds: 5000

      - name: Turning on...
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: httpdocs/app_offline.htm
          ignoreSSL: 1
